---
title: "Introduction to GCubeR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to GCubeR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
# Charge le package en développement local
if (requireNamespace("GCubeR", quietly = TRUE)) {
  library(GCubeR)
}

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

# Welcome to GCubeR

Forest quantification has become increasingly important in recent years.
Whether your goal is to anticipate financial flows, estimate standing timber value,
or quantify the carbon stored in your forest, working with tree volume equations
is rarely straightforward. Formulas are often difficult to find, coefficients vary
between species, and implementations can be tedious or error-prone.

GCubeR provides a unified and user-friendly toolbox that brings together the
most commonly used allometric equations in forestry. With only a few input
variables, the package handles all calculations for you.

GCubeR includes implementations of Algan, Rondeux, Dagnelie, and Vallet
volume equations, as well as CNIEFEB and Vallet's methods for estimating
biomass, carbon content, and CO₂ equivalent.

This vignette walks you through the workflow of applying GCubeR to your dataset
and shows how to extract the most useful information from your forest inventory.

---

# Global structure of GCubeR

## User input

To use **GCubeR**, the user must provide a data frame with at least:

- `c130`: stem circumference at 1.30 m height (cm)  
- `species_code`: full Latin species name in uppercase, e.g. \"QUERCUS_ROBUR\"

To be able to use **all** functions in the package, your data frame should contain:

- `c130`: stem circumference at 1.30 m height (cm)  
- `species_code`: species Latin name in uppercase (e.g. \"FAGUS_SYLVATICA\")  
- `hdom`: dominant height (m)  
- `htot`: total tree height (m)  
- `dbh`: diameter at breast height (cm)

---

# Converting module

GCubeR provides tools to transform basic measurements so they fit the requirements
of the different volume and biomass equations:

- **`c150_c130`** : converts stem circumference measured at 1.50 m (c150)
  to circumference at 1.30 m (c130)
- **`add_c130_dbh`** : converts circumference at 1.30 m (c130) to
  diameter at breast height (dbh), and can also back-calculate c130
  from dbh when needed

---

# VTA module

The **VTA module** computes total aboveground volume (trunk + branches) using
three different methods.

## Rondeux 2 entry method (parametric) - `rondeux_vc22_vtot()`

This function compute VTA **AND** VC22

Available for the folowing `species_code`:

- `LARIX_SP`

Required column:

- `htot`
- `species_code`
- `c130`

Formula:

\[
v_{\mathrm{c22}} =
a_{\mathrm{vc22}}
\;+\;
b_{\mathrm{vc22}} \, c_{130}^{2} \, h_{\mathrm{tot}}
\]

\[
v_{\mathrm{vta}} =
a_{\mathrm{vtot}} \, c_{130}^{2} \, h_{\mathrm{tot}}
\]

All coefficients used in this model are provided in the dataset `rondeux_vc22_vtot()`.  
You can load them with:

data("rondeux_vc22_vtot", package = "GCubeR")

### Bouvard method (parametric) — `bouvard_vta()`

Required columns:

- `dbh`
- `species_code`
- `htot`

Available for the folowing `species_code` :

- `QUERCUS_SP`

Formula:

\[
v_{\mathrm{vta}} = 0.5 \times \left(\frac{dbh}{100}\right)^2 \times h_{tot}
\]

`dbh` is in cm, `htot` in m, result in m³ per tree.

---

### Algan method (parametric) — `algan_vta_vc22()`

Required columns:

- `dbh`
- `species_code`
- `htot`

Available for the following `species_code`:

- `ABIES_ALBA`

Formula:

\[
v_{\mathrm{vta}} = 0.4 \times \left(\frac{dbh}{100}\right)^2 \times h_{tot}
\]

---

### Vallet method — `vallet_vta()`

Required columns:

- `c130`
- `species_code`
- `htot`

Available for the following species:

- `PICEA_ABIES`  
- `QUERCUS_ROBUR`  
- `FAGUS_SYLVATICA`  
- `PINUS_SYLVESTRIS`  
- `PINUS_PINASTER`  
- `ABIES_ALBA`  
- `PSEUDOTSUGA_MENZIESII`  

Formula:

\[
\text{term}_{1,c}
= 
c \left( \frac{\sqrt{c_{130}}}{h_{\mathrm{tot}}} \right)
\]

\[
\text{term}_{2,d}
=
1 + \frac{d}{c_{130}^{2}}
\]

\[
\mathrm{form}
=
\left( a + b\,c_{130} + \text{term}_{1,c} \right)
\;\times\;
\text{term}_{2,d}
\]


\[
v_{\mathrm{vta}} =
\mathrm{form} \times \frac{1}{\pi \cdot 40000} \times c_{130}^2 \times h_{tot}
\]

All coefficients used in this model are provided in the dataset `vallet_vta()`.  
You can load them with:

data("vallet_vta", package = "GCubeR")

---

# VC22 module

The **VC22 module** computes the trunk volume until 22 cm circumference using different
methods.

## Non parametric equations

The non parametric equations are based on empirical volume tables which give them 
a better fitness for trees evaluated in the same environment as those used for model construction.

---

### Dagnelie single-entry method — `dagnelie_vc22_1()`

Required columns:

- `c130`
- `species_code`

Available for the following `species_code`:
<div style="display: flex; gap: 40px;">

<div style="flex: 1;">

- `ABIES_ALBA`
- `ACER_CAMPESTRE`
- `ACER_PLATANOIDES`
- `ACER_PSEUDOPLATANUS`
- `AESCULUS_HIPPOCASTANUM`
- `ALNUS_GLUTINOSA`
- `ALNUS_INCANA`
- `BETULA_SP`
- `CARPINUS_SP`
- `CASTANEA_SATIVA`
- `CORLYUS_AVELLANA`
- `CRATAEGUS_SP`
- `CUPRESSUS_SP`
- `FAGUS_SYLVATICA`
- `FRAXINUS_EXCELSIOR`
- `JUNGLANS_SP`
- `LARIX_SP`
- `MALUS_SP`
- `PICEA_ABIES`
- `PICEA_SITCHENSIS`
- `PINUS_LARICIO`
- `PINUS_NIGRA`
- `PINUS_SYLVESTRIS`

</div>

<div style="flex: 1;">


- `POPULUS_TREMULA`
- `POPULUSxCANADENSIS`
- `PRUNUS_AVIUM`
- `PRUNUS_CERASUS`
- `PRUNUS_SP`
- `PSEUDOTSUGA_MENZIESII`
- `PYRUS_SP`
- `QUERCUS_PETRAEA`
- `QUERCUS_PUBESCENS`
- `QUERCUS_ROBUR`
- `QUERCUS_RUBRA`
- `QUERCUS_SP`
- `RHAMNUS_FRANGULA`
- `ROBINIA_PSEUDOACACIA`
- `SALIX_SP`
- `SAMBUCUS_SP`
- `SORBUS_ARIA`
- `SORBUS_AUCUPARIA`
- `TAXUS_BACCATA`
- `THUJA_PLICATA`
- `TILIA_SP`
- `ULMUS_SP`

</div>

</div>

Formula:

\[
v_{\mathrm{c22}} = 
a \;+\; b\,c_{130} \;+\; c\,c_{130}^2 \;+\; d\,c_{130}^3
\]


All coefficients used in this model are provided in the dataset `dan1`.  
You can load them with:

`data("dan1", package = "GCubeR")`

### Graduated single-entry Dagnelie method — `dagnelie_vc22_1g()`

Required columns:

- `c130`
- `species_code`
- `hdom`

Available for the following `species_code`:

see at Dagnelie single entry method

Formula:

\[
v_{\mathrm{c22}} =
a \;+\;
b\,c_{130} \;+\;
c\,c_{130}^{2} \;+\;
d\,c_{130}^{3} \;+\;
e\,h_{\mathrm{dom}} \;+\;
f\,h_{\mathrm{dom}}\,c_{130}^{2}
\]

All coefficients used in this model are provided in the dataset `dan1g`.  
You can load them with:

data("dan1g", package = "GCubeR")

### Dagnelie two entry model - `dagnelie_vc22_2()`

Required column:

- `c130`
- `species_code`
- `htot`

Available for the folowing `species_code`:

See at Dagnelie single entry method

Formula :

\[
v =
a \;+\;
b\,c_{130}
\;+\;
c\,c_{130}^{2}
\;+\;
d\,c_{130}^{3}
\;+\;
e\,h_{\mathrm{tot}}
\;+\;
f\,h_{\mathrm{tot}}\,c_{130}^{2}
\]


All coefficients used in this model are provided in the dataset `dan2`.  
You can load them with:

data("dan2", package = "GCubeR")

## Parametric equations

Parametric models provide stable and interpretable equations that remain valid 
across a wide range of tree dimensions.

### Vallet 2 entry method - `vallet_vc22()`

Required columns:

- `dbh`
- `species_code`
- `htot`

Available for the folowing `species_code`:
<div style="display: flex; gap: 40px;">

<div style="flex: 1;">


- `QUERCUS_ROBUR`
- `QUERCUS_PETRAEA`
- `QUERCUS_PUBESCENS`
- `FAGUS_SYLVATICA`
- `PINUS_PINASTER`
- `PINUS_SYLVESTRIS`

</div>

<div style="flex: 1;">

- `PINUS_LARICIO`
- `PINUS_NIGRA`
- `PINUS_HALEPENSIS`
- `PICEA_ABIES`
- `ABIES_ALBA`
- `PSEUDOTSUGA_MENZIESII`

</div>

</div>

Formula:

\[
\text{term}_{1,a} = a \times \left( \frac{h_{\mathrm{tot}}}{dbh} \right)
\]

\[
\text{term}_{2,bc} = b \;+\; c \, dbh
\]

\[
\text{term}_{3,\mathrm{geom}} =
\frac{\pi \, dbh^{2} \, h_{\mathrm{tot}}}{40}
\]

\[
v_{\mathrm{c22,dm3}} =
\text{term}_{1,a}
\;+\;
\text{term}_{2,bc} \times \text{term}_{3,\mathrm{geom}}
\]

All coefficients used in this model are provided in the dataset `vallet_vc22()`.  
You can load them with:

data("vallet_vc22", package = "GCubeR")

### Rondeux 2 entry method - `rondeux_vc22_vtot()`

This function compute VTA **AND** VC22

Available for the folowing `species_code`:

- `LARIX_SP`

Required column:

- `htot`
- `species_code`
- `c130`

Formula:

\[
v_{\mathrm{c22}} =
a_{\mathrm{vc22}}
\;+\;
b_{\mathrm{vc22}} \, c_{130}^{2} \, h_{\mathrm{tot}}
\]

\[
v_{\mathrm{vta}} =
a_{\mathrm{vtot}} \, c_{130}^{2} \, h_{\mathrm{tot}}
\]

# Merchendising volume

Regroup all soldable part of the trunc and branches 


